version: 2.1
jobs:
  build:
    docker:
      - image: raphaelcastro35/ruby_gems_fleury:0.2.0
    working_directory: ~/qa_teste_web_vr
    steps:
      - checkout
      - save_cache:
          key: grt-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/qa_teste_web_vr

  bundle_dependencies:
    working_directory: ~/qa_teste_web_vr 
    docker:
      - image: raphaelcastro35/ruby_gems_fleury:0.2.0
    steps:
      - restore_cache:
          keys:
            - grt-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - grt-bundle-{{ .Branch }}
      - run: 
          name: Bundle install
          command: bundle install --path vendor/bundle
      - save_cache:
          key: grt-bundle-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/qa_teste_web_vr/vendor/bundle
      - save_cache:
          key: grt-bundle-{{ .Branch }}
          paths: 
            - ~/qa_teste_web_vr/vendor/bundle
  chrome_test:
    working_directory: ~/qa_teste_web_vr
    docker:
      - image: raphaelcastro35/ruby_gems_fleury:0.2.0
    steps:
      - restore_cache:
          keys:
            - grt-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - grt-bundle-{{ .Branch }}
      - run: 
          name: Bundle install
          command: bundle install --path vendor/bundle
      - run: 
          name: Execute all features scenarios
          command: bundle exec cucumber 
      - store_test_results:
          path: ~/cucumber/junit.xml
      - store_artifacts:
          path: ~/cucumber/junit.xml

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - bundle_dependencies:
          requires: 
            - build
      - code_analyzer:
          requires:
            - bundle_dependencies
      - chrome_test:
          requires:
            - bundle_dependencies
